on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip poetry
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          poetry version ${GITHUB_REF##*/}
          poetry build
          ls dist
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="${GITHUB_REF##*/}"
          hub release edit $(find ./dist/ -type f -printf "-a %p ") -m "" "$tag_name"
      - name: Upload Release to GCP
        uses: google-github-actions/upload-cloud-storage@v0.2.0
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          path: ${{ $(find dist -type f -name "*.whl") }}
          destination: gwasqc/releases/${{ $(basename $(find dist -type f -name "*.whl")) }}
